### PR TITLE
Added authentication upon login; set up routes to create users, get users, and verify users; set up cookie middleware

### PR DESCRIPTION
**Pull request by clarcheveque**
### Authentication Updates

Added the following to Docketeer:

1. Created login and signup routers
2. Created signupController to check that username does not already exist in database and password meets the requirements.
3. Created cookieController to set cookies and set SSID cookie.
4. Created userController to create new user in database, get all users from database (for system admin), and verify that user's password is correct.
5. Installed bcrypt and successfully hashed password. Still working on sending hashed password to database.
6. Linked login frontend to backend so Docketeer displays various error messages as alerts and sends authenticated users to home page.

### Known Bugs

1. Experienced problem sending hashed password to database. Will continue to work on this.

### CODE REVIEW

**Review by ajsmith925 — APPROVED** [review]
great work on setting up our backend!

**Review by griffinrogersilver — APPROVED** [review]
Beautiful work!

**Review by charcharryu — APPROVED** [review]
great job clarcheveque. Thank you for the login signup routes and middleware

**Review by lo-guevara — APPROVED** [review]
Thanks for adding in server authentication functionality. Will now work on front end to incorporate the data you send back to be saved in the redux store.

**Pull request merged**
