### PR TITLE
adds updated demo to README

### PR DESCRIPTION
**Pull request by garrettallen0**
co-author: adriankormier

adriankormier@gmail.com

co-author: shao-shuai

shuai-shao@outlook.com

co-author: KwonJiyongGD

micliu@ucdavis.edu

co-author : jayoo0621

jayoo0621@gmail.com

### CODE REVIEW

**Review by adriankormier — APPROVED** [review]
LGTM!

**Review by shao-shuai — APPROVED** [review]
looks great!

**Review by KwonJiyongGD — APPROVED** [review]
Let's go team!

**Review by jayoo0621 — APPROVED** [review]
Looks good!! 💯

**Pull request merged**
