### PR TITLE
fixed routing bugs on login page and main app with react-router Router wrappers

### PR DESCRIPTION
**Pull request by clarcheveque**
### Fixed Bug

1. After adding routing from the login component to the app component with react-router, the nav bar link routing stopped working. We resolved this by wrapping the react-router BrowserRouter around the redirect and switch in our login component and the render in our app component.

Co-authored-by: Lorenzo Guevara 16786959+lo-guevara@users.noreply.github.com

### CODE REVIEW

**Review by charcharryu — APPROVED** [review]
great bug fix

**Review by lo-guevara — APPROVED** [review]
Reviewed. Ok to merge to master, thanks for squashing those bugs.

**Review by ajsmith925 — APPROVED** [review]
merge approved

**Review by griffinrogersilver — APPROVED** [review]
Jesus, who hired this guy

**Pull request merged**
