### PR TITLE
added patch install and troubleshoot for network capacity in readme

### PR DESCRIPTION
**Pull request by shao-shuai**
co-author : adriankormier <adriankormier@gmail.com>
co-author : garrettallen0 <Garrett.allen13@gmail.com>
co-author : KwonJiyongGD <micliu@ucdavis.edu>
co-author : jayoo0621 <jayoo0621@gmail.com>

### CODE REVIEW

**Review by jayoo0621 — APPROVED** [review]
Great job!

**Review by garrettallen0 — APPROVED** [review]
Looks good!

**Review by adriankormier — APPROVED** [review]
LGTM!

**Review by KwonJiyongGD — APPROVED** [review]
Reviewed and Approved!

**Pull request merged**
