### PR TITLE
Docketeer 6/17 MVP Version

### PR DESCRIPTION
**Pull request by lo-guevara**
This was the version showcased for MVP to the broader group:

Co-authored-by: Griffin Silver <74221399+griffinrogersilver@users.noreply.github.com>
Co-authored-by: Alex Smith <74221399+ajsmith925@users.noreply.github.com>
Co-authored-by: Charles Ryu <78817594+charcharryu@users.noreply.github.com>
Co-authored-by: Catherine Larcheveque <79517320+clarcheveque@users.noreply.github.com>

### CODE REVIEW

**Review by ajsmith925 — APPROVED** [review]
thanks for making a PR of our MVP for the rest of us to pull

**Review by charcharryu — APPROVED** [review]
Good refactoring.

**Review by griffinrogersilver — APPROVED** [review]
Love the new features and the added security with creating Admin roles!

**Review by clarcheveque — APPROVED** [review]
Great job on the MVP everyone!

**Pull request merged**
