### PR TITLE
Merging changes from Cat's end as well as adding additional update functionality to client.

### PR DESCRIPTION
**Pull request by lo-guevara**
**Features Added**

1. added following forms to the Settings tab in Docketeer
-  password update
-  email update
-  phone number update
2.  added corresponding backend routers and middleware functions to handle update actions
- updatePassword
-  updateEmail
-  updatePhone
3. Merged automated nodeMailer emails from Cat's branch
4. Added more fixes to the notification system such as fixing the bug where the cpu_threshold and mem_threshold were switched resulting in inaccurate notifications
5. Added user input edge case handlers for phone numbers, emails, and password confirmations

**Next steps**

1. add testing for reducer functions as well as supertests for routes to confirm functionality is as expected
2. hook into event emitter class and incorporate the observer design pattern in our notification system
3. for postgresql cloud methods that return all columns for a particular user, we need to update queries to pull all columns BUT the password column. It presents a security concern if we continually send the client their password, even if it is hashed. This is a quick fix that should be prioritized.

Co-authored-by: Griffin Silver 74221399+griffinrogersilver@users.noreply.github.com
Co-authored-by: Alex Smith 74221399+ajsmith925@users.noreply.github.com
Co-authored-by: Charles Ryu 78817594+charcharryu@users.noreply.github.com
Co-authored-by: Catherine Larcheveque 79517320+clarcheveque@users.noreply.github.com

### CODE REVIEW

**Review by charcharryu — APPROVED** [review]
good merge. Hopefully this will work on my machine too 🔵

**Review by clarcheveque — APPROVED** [review]
Thanks for connecting the routes. And great job debugging, as always!

**Review by ajsmith925 — APPROVED** [review]
great work, thanks Zo!

**Review by griffinrogersilver — APPROVED** [review]
Great work!!

**Pull request merged**
