### PR TITLE
refactor networkListContainers with Promise.all

### PR DESCRIPTION
**Pull request by shao-shuai**
co-author : adriankormier <adriankormier@gmail.com>
co-author : garrettallen0 <Garrett.allen13@gmail.com>
co-author : KwonJiyongGD <micliu@ucdavis.edu>
co-author : jayoo0621 <jayoo0621@gmail.com>

### CODE REVIEW

**Review by jayoo0621 — APPROVED** [review]
Great Job! 👍

**Review by adriankormier — APPROVED** [review]
LGTM!

**Review by garrettallen0 — APPROVED** [review]
Great work, Shuai!

**Review by KwonJiyongGD — APPROVED** [review]
Reviewed and Approved the use of Promise.all to increase time efficiency

**Pull request merged**
