### PR TITLE
John/remove disconnect button on docketeer default

### PR DESCRIPTION
**Pull request by jayoo0621**
co-author: adriankormier [adriankormier@gmail.com]
co-author: garrettallen0 [Garrett.allen13@gmail.com]
co-author: shao-shuai [shuai-shao@outlook.com]
co-author: KwonJiyongGD [micliu@ucdavis.edu]

### CODE REVIEW

**Review by shao-shuai — APPROVED** [review]
good job!

**Review by KwonJiyongGD — APPROVED** [review]
Edge case handling! Wooo!

**Review by adriankormier — APPROVED** [review]
Great work John!

**Review by garrettallen0 — APPROVED** [review]
Great work

**Pull request merged**
