### PR TITLE
Minor changes and cleanup to prepare Docketeer 3.0 for launch

### PR DESCRIPTION
**Pull request by lo-guevara**
Minor changes and cleanup to prepare Docketeer 3.0 for launch

**Changes**
1. removed some console logs
2. updated nodeMailer transport arguments to use variables from file in /security/email/ (which is in .gitignore)
3. removed database connection URI, preparing for launch

**Additional housework before launch**
- clean up more console logs
- go through files and add file headers

Co-authored-by: Griffin Silver <74221399+griffinrogersilver@users.noreply.github.com>
Co-authored-by: Alex Smith <74221399+ajsmith925@users.noreply.github.com>
Co-authored-by: Charles Ryu <78817594+charcharryu@users.noreply.github.com>
Co-authored-by: Catherine Larcheveque <79517320+clarcheveque@users.noreply.github.com>

### CODE REVIEW

**Review by griffinrogersilver — APPROVED** [review]
Great email event emitter!

**Review by ajsmith925 — APPROVED** [review]
Thanks for taking the time to parse through our code and clean it up to prepare for launch

**Review by charcharryu — APPROVED** [review]
Great, E-mails looking good.

**Review by clarcheveque — APPROVED** [review]
Thanks for cleaning up our code!

**Pull request merged**
