### PR TITLE
Added email notifications for signup and container issues, automated the creation of tables/user roles in custom user databases

### PR DESCRIPTION
**Pull request by clarcheveque**
### Problem
1. Upon signup, users do not receive any notification to confirm a successful signup. At this point, we also miss an opportunity to connect with our users.
2. Docketeer's alert notifications were only configured to be sent via text message. Many people, especially in work settings, prefer email correspondence.
3. When system administrator's connect to their own database to manage the users of their organization, the database tables must be manually created, adding hassle to the onboarding process of Docketeer.

### New Features
The following new features have been added to Docketeer:

1.  Upon signup, the new user is sent a welcome email with username/password information. On click of the signup submit button, a client-side fetch request is routed through the apiRouter to the signupEmail middlware of the apiController. This middleware utilizes Nodemailer's transporter object to send a welcome email using Simple Mail Transfer Protocol (SMTP).
2. When a user's container stops or breaches a user-configured CPU/memory threshold, the user is sent an alert email to notify them of the issue. When Docketeer's event emitter catches a container issue, it sends a request to the backend and is routed through the apiController sendEmailAlert middleware. Using Nodemailer's transporter object, this middleware sends a different alert email to the user depending on the issue type. 
3. When a system administrator connects to their own database and then logs in, a query is automatically sent to populate the database with tables if they do not already exist. Every user's log in checks that these tables exist. This streamlines the onboarding process so users can quickly integrate and use Docketeer.

Co-authored-by: Charles Ryu <78817594+charcharryu@users.noreply.github.com>
Co-authored-by: Lorenzo Guevara <16786959+lo-guevara@users.noreply.github.com>
Co-authored-by: Alex Smith <74221399+ajsmith925@users.noreply.github.com>
Co-authored-by: Griffin Silver <74221399+griffinrogersilver@users.noreply.github.com>

### CODE REVIEW

**Review by ajsmith925 — APPROVED** [review]
phenomenal work on email notifications and automation

**Review by charcharryu — APPROVED** [review]
Controllers look great! Emails are gonna look awesome!

**Review by lo-guevara — APPROVED** [review]
Thanks for adding in the email notification functionality. Everything looks in good order here, but heard you were running into errors for the database table initialization. We can take a look into that later.

**Review by griffinrogersilver — APPROVED** [review]
Beautiful work! Clean implementation of the email notification system

**Pull request merged**
