### PR TITLE
John/refactor 404page

### PR DESCRIPTION
**Pull request by jayoo0621**
co-author: adriankormier [adriankormier@gmail.com]
co-author: garrettallen0 [Garrett.allen13@gmail.com]
co-author: shao-shuai [shuai-shao@outlook.com]
co-author: KwonJiyongGD [micliu@ucdavis.edu]
co-author : jayoo0621 [jayoo0621@gmail.com]

### CODE REVIEW

**Review by shao-shuai — APPROVED** [review]
great job!

**Review by adriankormier — APPROVED** [review]
LGTM!

**Review by garrettallen0 — APPROVED** [review]
Great work

**Review by KwonJiyongGD — APPROVED** [review]
Space Whale!

**Pull request merged**
