### PR TITLE
New features: Logout button fixed, added more rules to ESLinter, added Redux/React browser extensions for debugging, built out sessionsReducer and Redux store to support user roles and privileges functionality.

### PR DESCRIPTION
**Pull request by lo-guevara**
### Features

Added few new features here:
- transferred the login variables from local state to redux store and built out functionality in the sessionsReducer. 
- Also added different views depending on the users role pulled from db. 
- Additionally, added ability to save down user info in sessionsReducer store.
- Logout button fixed
- added more rules to ESLinter
- added Redux/React browser extensions for debugging

### Bug Fixes
1.  Logout functionality bug

**Issue Description:** After a user clicks the ‘logout’ button and logs out, React Router will redirect to the logout component. When a user tries to log back in, they are redirected back to Docketeer’s main dashboard. However, when the user tries to click any tabs on the left nav-bar, react-router will render a blank page.

**Root Cause:** The issue had to do with the way we were redirecting in react router and rendering components. After logging out, the user will be redirected back to login page, however the initial App Component (the entire dashboard) will still be rendered on the DOM. So after logging back in, an additional App component will be rendered to the DOM on top of the initial. ( Login > App > App ). This App component is identical to the previous one and will have the same switches, routers and routes. Thus navigating to ‘/setting’ by clicking the Settings tab will confuse react-router-dom since there are now two routes with endpoint ‘/setting’ resulting in blank page.

**Solution:** The solution is to not redirect from App component back to Login, rather to create a local state variable ‘loggedIn’ maintained at the Login component level and passing down its useState() function to App component. The logout button’s onClick property should be set to the function definition returned from useState(). Now when a user clicks logout, the Login component’s state variable is switched from true to false and the Login component will no longer render the App component. Logging back in will switch the loggedIn variable from false to true, and re-render the App component.

### CODE REVIEW

**Review by charcharryu — APPROVED** [review]
Thanks for getting the redux store ready for user roles and privileges!

**Review by griffinrogersilver — APPROVED** [review]
"He's a bad apple, sometimes..."

**Review by ajsmith925 — APPROVED** [review]
a lot of great features added, nice work Zo!

**Review by clarcheveque — APPROVED** [review]
Great work on the frontend! The dev tools you added are going to facilitate the development process for our team. Awesome solve on the logout bug, too.

**Pull request merged**
