### PR TITLE
Set up a server on port 3000, connected electron app to backend server

### PR DESCRIPTION
**Pull request by lo-guevara**
Problem: Requests made on the frontend electron app was not being properly routed to localhost:3000, but was instead being routed to localhost:9080.

Solution: 
- Client: using fetch request, and explicitly specifying the endpoint as localhost:3000.
- Server: using app.use(cors()) to allow ALL cors requests since we were initially getting allow same access origin CORS errors.
- adding global route handler to server file and sample route handler to test frontend/backend connectivity

Co-authored-by: Griffin Silver <74221399+griffinrogersilver@users.noreply.github.com>
Co-authored-by: Alex Smith <74221399+ajsmith925@users.noreply.github.com>
Co-authored-by: Charles Ryu <78817594+charcharryu@users.noreply.github.com>
Co-authored-by: Catherine Larcheveque <79517320+clarcheveque@users.noreply.github.com>

### CODE REVIEW

**Review by charcharryu — APPROVED** [review]
thank you lorenzo. god bless

**Review by clarcheveque — APPROVED** [review]
good job adding the headers to the fetch request!

**Review by ajsmith925 — APPROVED** [review]
solid additions

**Review by griffinrogersilver — APPROVED** [review]
Nicely done!

**Pull request merged**
