### PR TITLE
Backend

### PR DESCRIPTION
**Pull request by clarcheveque**
### Backend Updates

1. Used bcrypt to encrypt user passwords before storing into database for increased security. Used bcrypt compare method for authentication on user login. Stored bcrypt middleware in bcryptController file.
2. Created setAdminCookie middleware to return cookie with admin type if user is a verified admin. This runs on login and signup.
3. Removed setCookie middleware because it lacked functional use.
4. Changed postgres URI to link a different database under team Docketeer.
5. Deleted role column to streamline schema, but temporarily re-added column for use in the frontend. 
6. Added descriptions for all server files and deleted unnecessary or unused comments.

### Next Steps

1.  Refactor frontend queries to not be dependent on role column of user table.
2.  As a stretch feature, look into incorporating sessions for system admin tracking purposes.
3.  Configure application to allow users to implement their own database. To do this, we will have to query the user's database using the schema2 file.

### CODE REVIEW

**Review by charcharryu — APPROVED** [review]
The backend looks great! RIP to set cookies.

**Review by griffinrogersilver — APPROVED** [review]
Improved latency, nicely done

**Review by ajsmith925 — APPROVED** [review]
Got a lot done. Thanks for all the solid contributions, Cat!

**Review by lo-guevara — APPROVED** [review]
Thanks for this Cat!

**Pull request merged**
